force-app/logger/objects/Log_Setting__mdt/Log_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Log Setting</label>
    <pluralLabel>Log Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log_Setting__mdt/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <description>Freeform name for the system being logged, could be a a class name or an area of functionality</description>
    <inlineHelpText>Freeform name for the system being logged, could be a a class name or an area of functionality</inlineHelpText>
    <label>Component</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Log_Setting__mdt/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NONE</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>ERROR</fullName>
                <label>Error</label>
            </value>
            <value>
                <fullName>WARN</fullName>
                <label>Warn</label>
            </value>
            <value>
                <fullName>INFO</fullName>
                <label>Info</label>
            </value>
            <value>
                <fullName>DEBUG</fullName>
                <label>Debug</label>
            </value>
            <value>
                <fullName>FINE</fullName>
                <label>Fine</label>
            </value>
            <value>
                <fullName>FINER</fullName>
                <label>Finer</label>
            </value>
            <value>
                <fullName>FINEST</fullName>
                <label>Finest</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/logger/objects/Log_Setting__mdt/fields/LogMethod_Class__c.field-meta.xml
<CustomField>
    <fullName>LogMethod_Class__c</fullName>
    <defaultValue>&#39;nebc.DebugLogger&#39;</defaultValue>
    <description>Fully qualified name of an Apex Class implementing nebc.LogMethod, to do the logging</description>
    <inlineHelpText>Fully qualified name of an Apex Class implementing nebc.LogMethod, to do the logging</inlineHelpText>
    <label>LogMethod Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/logger/objects/Log_Setting__mdt/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <description>If provided, will only log data from the specified user id</description>
    <inlineHelpText>If provided, will only log data from the specified user id</inlineHelpText>
    <label>User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/logger/classes/Logger.cls
/**
 * @author aidan@nebulaconsulting.co.uk
 * @date 2019-03-19
 * @description Flexible logging framework that uses custom metadata to configure logging methods and levels
 */
global without sharing class Logger {

    /**
     * @description Logs a message with the specified logging level and component
     * @param logLevel The logging level (e.g., DEBUG, INFO, ERROR)
     * @param component The component name for categorizing logs
     * @param body The message or object to log
     */
    global static void log(System.LoggingLevel logLevel, String component, Object body) {
        log(logLevel, component, body, null);
    }

    /**
     * @description Logs a message with the specified logging level, component, and related record
     * @param logLevel The logging level (e.g., DEBUG, INFO, ERROR)
     * @param component The component name for categorizing logs
     * @param body The message or object to log
     * @param relatedTo Optional Id of a related record
     */
    global static void log(System.LoggingLevel logLevel, String component, Object body, Id relatedTo) {
        new LazySObjectIterator(componentToLogSetting.getAll(component))
                .setDefaultIfEmpty(new Log_Setting__mdt(LogMethod_Class__c = DebugLogger.class.getName(), Level__c = logLevel.name()))
                .filter(new IsActiveLogLevel(logLevel))
                .forEach(new WriteLog(logLevel, component, body, relatedTo));
    }

    private class IsActiveLogLevel implements BooleanFunction {

        private LoggingLevel logLevel;

        public IsActiveLogLevel(LoggingLevel logLevel) {
            this.logLevel = logLevel;
        }

        public Boolean isTrueFor(Object o) {
            Log_Setting__mdt thisSetting = (Log_Setting__mdt)o;
            return logLevel.ordinal() >= Logger.logLevelToPriority.get(thisSetting.Level__c);
        }
    }

    private class WriteLog implements VoidFunction {

        private System.LoggingLevel logLevel;
        private String component;
        private Object body;
        private Id relatedTo;

        public WriteLog(System.LoggingLevel logLevel, String component, Object body, Id relatedTo) {
            this.logLevel = logLevel;
            this.component = component;
            this.body = body;
            this.relatedTo = relatedTo;
        }

        public void call(Object o) {
            Log_Setting__mdt thisSetting = (Log_Setting__mdt)o;
            getLogMethod(thisSetting.LogMethod_Class__c).log(logLevel, component, body, relatedTo);
        }
    }

    /**
     * @description Commits all pending logs to their respective log methods
     */
    global static void commitLogs() {
        for(LogMethodObject thisActiveMethod : activeLogMethods.values()) {
            thisActiveMethod.commitLogs();
        }
    }

    private static LogMethodObject getLogMethod(String logMethodName) {
        LogMethodObject activeLogMethod = activeLogMethods.get(logMethodName);
        if(activeLogMethod == null) {
            Type logMethodType = TypeLoader.getType(logMethodName);

            if (logMethodType == null) {
                throw new ClassNotFoundException('No log method found matching class name ' + logMethodName + '. Is the class global? Does it include any required namespace?');
            }

            Object newInstance = logMethodType.newInstance();
            if(newInstance instanceof LogMethodObject) {
                activeLogMethod = ((LogMethodObject)newInstance);
            } else {
                activeLogMethod = new LogMethodToLogMethodObject((LogMethod)newInstance);
            }

            activeLogMethods.put(logMethodName, activeLogMethod);
        }
        return activeLogMethod;
    }

    @TestVisible
    private static List<Log_Setting__mdt> logSettings {get {
        if(logSettings == null) {
            logSettings = [
                    SELECT Component__c, User_Id__c, Level__c, LogMethod_Class__c
                    FROM Log_Setting__mdt
            ];
        }
        return logSettings;
    } set;}

    private static SObjectIndex componentToLogSetting {get {
        if(componentToLogSetting == null) {
            componentToLogSetting = new SObjectIndex(Log_Setting__mdt.Component__c).putAll(logSettings);
        }
        return componentToLogSetting;
    } set;}


    private static Map<String, Integer> logLevelToPriority {get {
        if(logLevelToPriority == null) {
            logLevelToPriority = new Map<String, Integer>();
            List<LoggingLevel> logLevels = LoggingLevel.values();

            for(Integer i=0; i < logLevels.size(); i++) {
                logLevelToPriority.put(logLevels[i].name(), logLevels[i].ordinal());
            }
        }
        return logLevelToPriority;
    } set;}

    private static Map<String, LogMethodObject> activeLogMethods = new Map<String, LogMethodObject>();
}