force-app/logger/objects/Log_Setting__mdt/Log_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Log Setting</label>
    <pluralLabel>Log Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log_Setting__mdt/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <description>Freeform name for the system being logged, could be a a class name or an area of functionality</description>
    <inlineHelpText>Freeform name for the system being logged, could be a a class name or an area of functionality</inlineHelpText>
    <label>Component</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Log_Setting__mdt/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NONE</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>ERROR</fullName>
                <label>Error</label>
            </value>
            <value>
                <fullName>WARN</fullName>
                <label>Warn</label>
            </value>
            <value>
                <fullName>INFO</fullName>
                <label>Info</label>
            </value>
            <value>
                <fullName>DEBUG</fullName>
                <label>Debug</label>
            </value>
            <value>
                <fullName>FINE</fullName>
                <label>Fine</label>
            </value>
            <value>
                <fullName>FINER</fullName>
                <label>Finer</label>
            </value>
            <value>
                <fullName>FINEST</fullName>
                <label>Finest</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/logger/objects/Log_Setting__mdt/fields/LogMethod_Class__c.field-meta.xml
<CustomField>
    <fullName>LogMethod_Class__c</fullName>
    <defaultValue>&#39;nebc.DebugLogger&#39;</defaultValue>
    <description>Fully qualified name of an Apex Class implementing nebc.LogMethod, to do the logging</description>
    <inlineHelpText>Fully qualified name of an Apex Class implementing nebc.LogMethod, to do the logging</inlineHelpText>
    <label>LogMethod Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/logger/objects/Log_Setting__mdt/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <description>If provided, will only log data from the specified user id</description>
    <inlineHelpText>If provided, will only log data from the specified user id</inlineHelpText>
    <label>User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Logger.cls
/**
 * @author aidan@nebulaconsulting.co.uk
 * @date 2019-03-19
 */

global without sharing class Logger {

    global static void log(System.LoggingLevel logLevel, String component, String body) {
        log(logLevel, component, body, null);
    }

    global static void log(System.LoggingLevel logLevel, String component, String body, Id relatedTo) {
        Log_Setting__mdt thisSetting = componentToLogSetting.get(component);
        if(thisSetting == null) {
            thisSetting = new Log_Setting__mdt(LogMethod_Class__c = DebugLogger.class.getName(), Level__c = logLevel.name());
        }

        if(logLevel.ordinal() >= logLevelToPriority.get(thisSetting.Level__c)) {
            getLogMethod(thisSetting.LogMethod_Class__c).log(logLevel, component, body, relatedTo);
        }
    }

    global static void commitLogs() {
        for(LogMethod thisActiveMethod : activeLogMethods.values()) {
            thisActiveMethod.commitLogs();
        }
    }

    private static LogMethod getLogMethod(String logMethodName) {
        LogMethod activeLogMethod = activeLogMethods.get(logMethodName);
        if(activeLogMethod == null) {
            Type logMethodType = TypeLoader.getType(logMethodName);
            if (logMethodType == null) {
                throw new ClassNotFoundException('No log method found matching class name ' + logMethodName + '. Is the class global? Does it include any required namespace?');
            }
            activeLogMethod = ((LogMethod) logMethodType.newInstance());
            activeLogMethods.put(logMethodName, activeLogMethod);
        }
        return activeLogMethod;
    }

    @TestVisible
    private static List<Log_Setting__mdt> logSettings {get {
        if(logSettings == null) {
            logSettings = [
                    SELECT Component__c, User_Id__c, Level__c, LogMethod_Class__c
                    FROM Log_Setting__mdt
            ];
        }
        return logSettings;
    } set;}

    private static Map<String, Log_Setting__mdt> componentToLogSetting {get {
        if(componentToLogSetting == null) {
            componentToLogSetting = new Map<String, Log_Setting__mdt>();
            for(Log_Setting__mdt thisSetting : logSettings) {
                componentToLogSetting.put(thisSetting.Component__c, thisSetting);
            }
        }
        return componentToLogSetting;
    } set;}


    private static Map<String, Integer> logLevelToPriority {get {
        if(logLevelToPriority == null) {
            logLevelToPriority = new Map<String, Integer>();
            List<LoggingLevel> logLevels = LoggingLevel.values();

            for(Integer i=0; i < logLevels.size(); i++) {
                logLevelToPriority.put(logLevels[i].name(), logLevels[i].ordinal());
            }
        }
        return logLevelToPriority;
    } set;}

    private static Map<String, LogMethod> activeLogMethods = new Map<String, LogMethod>();
}