force-app/logger/objects/Log_Setting__mdt/Log_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Log Setting</label>
    <pluralLabel>Log Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log_Setting__mdt/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <description>Freeform name for the system being logged, could be a a class name or an area of functionality</description>
    <inlineHelpText>Freeform name for the system being logged, could be a a class name or an area of functionality</inlineHelpText>
    <label>Component</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Log_Setting__mdt/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NONE</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>ERROR</fullName>
                <label>Error</label>
            </value>
            <value>
                <fullName>WARN</fullName>
                <label>Warn</label>
            </value>
            <value>
                <fullName>INFO</fullName>
                <label>Info</label>
            </value>
            <value>
                <fullName>DEBUG</fullName>
                <label>Debug</label>
            </value>
            <value>
                <fullName>FINE</fullName>
                <label>Fine</label>
            </value>
            <value>
                <fullName>FINER</fullName>
                <label>Finer</label>
            </value>
            <value>
                <fullName>FINEST</fullName>
                <label>Finest</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/logger/objects/Log_Setting__mdt/fields/LogMethod_Class__c.field-meta.xml
<CustomField>
    <fullName>LogMethod_Class__c</fullName>
    <defaultValue>&#39;nebc.DebugLogger&#39;</defaultValue>
    <description>Fully qualified name of an Apex Class implementing nebc.LogMethod, to do the logging</description>
    <inlineHelpText>Fully qualified name of an Apex Class implementing nebc.LogMethod, to do the logging</inlineHelpText>
    <label>LogMethod Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DebugLoggerTest.cls
/**
 * @author aidan@nebulaconsulting.co.uk
 * @date 2019-03-19
 */

@IsTest
private class DebugLoggerTest {

    @IsTest
    static void testBehavior() {
        Logger.log(LoggingLevel.DEBUG, DebugLoggerTest.class.getName(), 'A message');
    }

    @IsTest
    static void noSuchLoggerClass() {
        Logger.logSettings = new List<Log_Setting__mdt>{ new Log_Setting__mdt(
            Level__c = LoggingLevel.DEBUG.name(),
                Component__c = DebugLoggerTest.class.getName(),
                LogMethod_Class__c = 'noSuchClass'
        )};
        try {
            Logger.log(LoggingLevel.DEBUG, DebugLoggerTest.class.getName(), 'A message');
        } catch (ClassNotFoundException e) {
            return;
        }
        System.assert(false, 'Expected a ClassNotFoundException');
    }
}