force-app/main/default/objects/Test_Record_Generator__mdt/Test_Record_Generator__mdt.object-meta.xml
<CustomObject>
    <description>Specifies an Apex class that can generate valid test objects for a particular type</description>
    <label>Test Record Generator</label>
    <pluralLabel>Test Record Generators</pluralLabel>
</CustomObject>

force-app/main/default/objects/Test_Record_Generator__mdt/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <description>Include namespace, if applicable. Nested classes can be used</description>
    <inlineHelpText>Include namespace, if applicable. Nested classes can be used</inlineHelpText>
    <label>Apex Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Record_Generator__mdt/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Highest priority for a particular SObject and Variant is used. So, a package can define a way of creating a Contact which is then overridden by a higher priority defined in another package with adds required fields</description>
    <inlineHelpText>Highest priority for a particular SObject and Variant is used. So, a package can define a way of creating a Contact which is then overridden by a higher priority defined in another package with adds required fields</inlineHelpText>
    <label>Priority</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/testRecordGenerator/objects/Test_Record_Generator__mdt/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>Developer name of the SObject</description>
    <inlineHelpText>Developer name of the SObject</inlineHelpText>
    <label>SObject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestRecordSourceTest.cls
/**
 * @author aidan@nebulaconsulting.co.uk
 * @date 2019-03-04
 */

@IsTest
private class TestRecordSourceTest {

    static TestRecordSource testRecordSource = new TestRecordSource();

    @IsTest
    static void noMatchingMetadata() {
        testRecordSource = new TestRecordSource();

        try {
            testRecordSource.getRecord(Account.SObjectType).withInsert();
        } catch (ClassNotFoundException e) {
            String message = e.getMessage();
            System.assert(message.contains('No Test_Record_Generator__mdt found'));
            return;
        }
        System.assert(false, 'Should have thrown exception');
    }

    @IsTest
    static void noApexClassImplementation() {
        String className = 'noSuchClass';

        testRecordSource.addTemporaryMetadata(
                new Test_Record_Generator__mdt(
                        Apex_Class__c = className,
                        Priority__c = 0,
                        SObject__c = 'Account'
                ));

        try {
            testRecordSource.getRecord(Account.SObjectType).withInsert();
        } catch (ClassNotFoundException e) {
            String message = e.getMessage();
            System.assert(message.contains(className));
            return;
        }
        System.assert(false, 'Should have thrown exception');
    }

    @IsTest
    static void setMetadata() {
        String accountName = 'Some wacky thing not in the metadata';

        testRecordSource.addTemporaryMetadataFromInstance(new Account(Name = accountName), 0);

        Account result = (Account)testRecordSource.getRecord(Account.SObjectType).withoutInsert();

        System.assertEquals(accountName, result.Name);
    }
}