force-app/main/default/objects/Test_Record_Generator__mdt/Test_Record_Generator__mdt.object-meta.xml
<CustomObject>
    <description>Specifies an Apex class that can generate valid test objects for a particular type</description>
    <label>Test Record Generator</label>
    <pluralLabel>Test Record Generators</pluralLabel>
</CustomObject>

force-app/main/default/objects/Test_Record_Generator__mdt/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <description>JSON parameters used to initialise the TestRecordGenerator</description>
    <inlineHelpText>JSON parameters used to initialise the TestRecordGenerator</inlineHelpText>
    <label>Parameters</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/testRecordGenerator/objects/Test_Record_Generator__mdt/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>Developer name of the SObject</description>
    <inlineHelpText>Developer name of the SObject</inlineHelpText>
    <label>SObject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestMetadataRecordGeneratorTest.cls
/**
 * @author aidan@nebulaconsulting.co.uk
 * @date 2019-03-06
 */

@IsTest
private class TestMetadataRecordGeneratorTest {

    static TestRecordSource testRecordSource = new TestRecordSource();
    static TestMetadataRecordGenerator generator = new TestMetadataRecordGenerator();

    @IsTest
    static void basicValue() {
        String accountName = 'ACME';
        generator.setup(
                testRecordSource,
                new Test_Record_Generator__mdt(
                        SObject__c = 'Account',
                        Parameters__c = JSON.serialize(
                                new Map<String, Object>{
                                        'Name' => new Map<String, Object>{
                                                'value' => accountName
                                        }
                                }
                        )
                )
        );
        Account generatedAccount = (Account)generator.getObjectNoInsert(null);

        System.assertEquals(accountName, generatedAccount.Name);
    }

    @IsTest
    static void appendRandomNumber() {
        String accountName = 'ACME';
        generator.setup(
                testRecordSource,
                new Test_Record_Generator__mdt(
                        SObject__c = 'Account',
                        Parameters__c = JSON.serialize(
                                new Map<String, Object>{'Name' => new Map<String, Object>{
                                        'valueFunction' =>
                                                new TestMetadataRecordGenerator.ValueFunction(
                                                        TestFieldFunctions.AppendRandomNumber.class.getName(),
                                                        new Map<String, Object>{
                                                                'value' => accountName
                                                        }
                                                )

                                }}
                        )
                )
        );
        Account generatedAccount = (Account)generator.getObjectNoInsert(null);

        System.assert(generatedAccount.Name.length() > accountName.length());
        System.assert(generatedAccount.Name.startsWith(accountName));
    }

    @IsTest
    static void parseDate() {
        Date birthDate = Date.newInstance(2019, 3, 5);
        generator.setup(
                testRecordSource,
                new Test_Record_Generator__mdt(
                        SObject__c = 'Contact',
                        Parameters__c = JSON.serialize(
                                new Map<String, Object>{'BirthDate' => new Map<String, Object>{
                                        'value' => birthDate
                                }
                                }
                        )
                )
        );
        Contact generatedContact = (Contact)generator.getObjectNoInsert(null);

        System.assertEquals(birthDate, generatedContact.Birthdate);
    }

    @IsTest
    static void parseDateTime() {
        Datetime closeDate = Datetime.now();

        generator.setup(
                testRecordSource,
                new Test_Record_Generator__mdt(
                        SObject__c = 'Case',
                        Parameters__c = JSON.serialize(
                                new Map<String, Object>{'ClosedDate' => new Map<String, Object>{
                                        'value' => closeDate
                                }
                                }
                        )
                )
        );
        Case generatedCase = (Case)generator.getObjectNoInsert(null);

        System.assertEquals(closeDate, generatedCase.ClosedDate);
    }

}