force-app/main/default/objects/Test_Record_Generator__mdt/Test_Record_Generator__mdt.object-meta.xml
<CustomObject>
    <description>Specifies an Apex class that can generate valid test objects for a particular type</description>
    <label>Test Record Generator</label>
    <pluralLabel>Test Record Generators</pluralLabel>
</CustomObject>

force-app/main/default/objects/Test_Record_Generator__mdt/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <description>Include namespace, if applicable. Nested classes can be used</description>
    <inlineHelpText>Include namespace, if applicable. Nested classes can be used</inlineHelpText>
    <label>Apex Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Record_Generator__mdt/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <description>JSON parameters used to initialise the TestRecordGenerator</description>
    <inlineHelpText>JSON parameters used to initialise the TestRecordGenerator</inlineHelpText>
    <label>Parameters</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Record_Generator__mdt/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Highest priority for a particular SObject and Variant is used. So, a package can define a way of creating a Contact which is then overridden by a higher priority defined in another package with adds required fields</description>
    <inlineHelpText>Highest priority for a particular SObject and Variant is used. So, a package can define a way of creating a Contact which is then overridden by a higher priority defined in another package with adds required fields</inlineHelpText>
    <label>Priority</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/testRecordGenerator/objects/Test_Record_Generator__mdt/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>Developer name of the SObject</description>
    <inlineHelpText>Developer name of the SObject</inlineHelpText>
    <label>SObject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/testRecordGenerator/objects/Test_Record_Generator__mdt/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <description>Optionally, name a variant of the type of object e.g. to distinguish creating a customer Contact from a supplier Contact</description>
    <inlineHelpText>Optionally, name a variant of the type of object e.g. to distinguish creating a customer Contact from a supplier Contact</inlineHelpText>
    <label>Variant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestRecords.cls
/**
 * @author aidan@nebulaconsulting.co.uk
 * @date 09/11/2018
 */
public inherited sharing class TestRecords {

    private static final String GENERATOR_SOBJECT_FIELD = Test_Record_Generator__mdt.SObject__c.getDescribe().getName();
    private static final String GENERATOR_VARIANT_FIELD = Test_Record_Generator__mdt.Variant__c.getDescribe().getName();

    private SObjectIndex generatorMetadata {get {
        if(generatorMetadata == null) {
            generatorMetadata = new SObjectIndex(
                    new List<String>{ GENERATOR_SOBJECT_FIELD, GENERATOR_VARIANT_FIELD})
                    .putAll(
                    [
                            SELECT Apex_Class__c, Priority__c, SObject__c, Variant__c, Parameters__c
                            FROM Test_Record_Generator__mdt
                            ORDER BY Priority__c ASC
                    ]);
        }
        return generatorMetadata;
    } set;}

    private Map<Id, TestRecordGenerator> generators;

    public TestRecords() {
        generators = new Map<Id, TestRecordGenerator>();
    }

    private TestRecordGenerator getGenerator(SObjectType objectType, String variant) {
        Test_Record_Generator__mdt thisGeneratorMetadata = (Test_Record_Generator__mdt) generatorMetadata.get(
                new Map<String, Object>{
                        GENERATOR_SOBJECT_FIELD => objectType.getDescribe().getName(),
                        GENERATOR_VARIANT_FIELD => variant
                });
        if(thisGeneratorMetadata == null) {
            throw new ClassNotFoundException(
                    'No Test_Record_Generator__mdt found for '
                            + objectType.getDescribe().getName()
                            + (variant != null ? ', variant: ' + variant : ''));
        } else {
            return getGenerator(thisGeneratorMetadata);
        }
    }

    private TestRecordGenerator getGenerator(Test_Record_Generator__mdt thisGeneratorMetadata) {
        TestRecordGenerator returnGenerator = generators.get(thisGeneratorMetadata.Id);
        if(returnGenerator == null) {
            returnGenerator = createGenerator(thisGeneratorMetadata);
        }
        return returnGenerator;
    }

    private TestRecordGenerator createGenerator(Test_Record_Generator__mdt thisGeneratorMetadata) {
        Type generatorType = TypeLoader.getType(thisGeneratorMetadata.Apex_Class__c);
        if (generatorType == null) {
            throw new ClassNotFoundException('No matching class found for ' + thisGeneratorMetadata.Apex_Class__c +
                    '. Check that it is global and that the namespace is included.');
        } else {
            TestRecordGenerator newGenerator = (TestRecordGenerator)TypeLoader.getInstance(generatorType, thisGeneratorMetadata.Parameters__c);
            newGenerator.parentTestRecords = this;
            generators.put(thisGeneratorMetadata.Id, newGenerator);
            return newGenerator;
        }
    }

    public SObject getObjectNoInsert(SObjectType objectType) {
        return getObjectNoInsert(objectType, null, null);
    }
    public SObject getObjectNoInsert(SObjectType objectType, String variant) {
        return getObjectNoInsert(objectType, variant, null);
    }
    public SObject getObjectNoInsert(SObjectType objectType, String variant, Map<String, Object> params) {
        return getGenerator(objectType, variant).getObjectNoInsert(params);
    }

    public SObject getObjectWithInsert(SObjectType objectType) {
        return getObjectWithInsert(objectType, null, null);
    }
    public SObject getObjectWithInsert(SObjectType objectType, String variant) {
        return getObjectWithInsert(objectType, variant, null);
    }
    public SObject getObjectWithInsert(SObjectType objectType, String variant, Map<String, Object> params) {
        return getGenerator(objectType, variant).getObjectWithInsert(params);
    }
}